# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html

# App name
spring.application.name=FitCenter Management System

# File paths
app.data.file-path=src/main/resources/data/trainers.txt
