# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html

# App name
spring.application.name=FitCenter Management System

# File paths
app.plans.file-path=src/main/resources/data/plans.txt
app.admins.file-path=src/main/resources/data/admins.txt
app.members.file-path=src/main/resources/data/members.txt
app.payments.file-path=src/main/resources/data/payments.txt
app.data.file-path=src/main/resources/data/trainers.txt
app.workout.file-path=src/main/resources/data/workouts.txt